#ifndef GUARD_CONFIG_RANDOMIZER_H
#define GUARD_CONFIG_RANDOMIZER_H

// Master switch. If FALSE, none of the randomizer code is compiled in.
#define RANDOMIZER_AVAILABLE   TRUE

#if RANDOMIZER_AVAILABLE == TRUE

#define RANDOMIZER_FLAG_WILD_MON               FLAG_RANDOMIZER_WILD_MON
#define RANDOMIZER_FLAG_TRAINER_MON            FLAG_RANDOMIZER_TRAINER_MON
#define RANDOMIZER_FLAG_STARTER_AND_GIFT_MON   FLAG_RANDOMIZER_STARTER_AND_GIFT_MON
#define RANDOMIZER_FLAG_FIELD_ITEMS            FLAG_RANDOMIZER_FIELD_ITEMS
#define RANDOMIZER_FLAG_ABILITIES              FLAG_RANDOMIZER_ABILITIES
#define RANDOMIZER_FLAG_TM_MOVES               FLAG_RANDOMIZER_TM_MOVES
#define RANDOMIZER_FLAG_MOVESETS               FLAG_RANDOMIZER_MOVESETS

// Percentage a random Pokemon can vary from the mon its being based on.
#define RANDOMIZER_BST_LENIENCY_PERCENT    10

// Number of moves in each randomized moveset.
#define RANDOMIZER_MOVESET_SIZE   21

// Number of mega stones available in each save pool.
#define RANDOMIZER_MEGA_STONE_POOL_SIZE   15

#endif // RANDOMIZER_AVAILABLE

#endif // GUARD_CONFIG_RANDOMIZER_H
