PetalburgCity_House2_MapScripts::
	.byte 0

PetalburgCity_House2_EventScript_Woman::
	msgbox PetalburgCity_House2_Text_NormanBecameGymLeader, MSGBOX_NPC
	end

PetalburgCity_House2_EventScript_SchoolKid::
	msgbox PetalburgCity_House2_Text_BattledNormanOnce, MSGBOX_NPC
	end

PetalburgCity_House2_Text_NormanBecameGymLeader:
	.string "REIN became our town's new\n"
	.string "GYM LEADER.\p"
	.string "I think she's really into horses\n"
	.string "and sorrow wind whatever that is.$"

PetalburgCity_House2_Text_BattledNormanOnce:
	.string "I battled REIN once, but, whew,\n"
	.string "she was way too strong.\p"
	.string "How would I put it?\p"
	.string "I just got the feeling that she\n"
	.string "lives for SNORLAX.$"

